apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
  namespace: encuesta
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 4
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: encuestaelcomite-back:k8s
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE_URL
          command:
            - /bin/sh
            - -c
            - |
              npm run db:migrate:diagram -w @encuestaelcomite/server
              npm run db:seed -w @encuestaelcomite/server
