apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: encuesta
type: Opaque
stringData:
  POSTGRES_USER: encuesta
  POSTGRES_PASSWORD: encuesta
  POSTGRES_DB: encuestaelcomite
  DATABASE_URL: postgresql://encuesta:encuesta@db:5432/encuestaelcomite
